### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by MaxAst** [chrisckchang/mean-contactlist-angular2#1]
When cloning the repo and running it with 'heroku local' I get the above error. I have all dependencies installed, downloaded npm and nodejs latest versions, and my config var for mLab seems to be fine too. Any ideas for what the problem is?

**Comment by chrisckchang** [comment]
It looks like the environment variable may not be set on your local machine. You'll likely need to do the following:

```
heroku config:get MONGODB_URI
// YOUR_MONGODB_URI printed here
export MONGODB_URI=YOUR_MONGODB_URI
```

**Comment by chrisckchang** [comment]
closing- feel free to reopen if this is still an issue.
