### ISSUE TITLE
Causing MEAN Stack app to crash upon initial load

### ISSUE THREAD

**Issue by braelyn-ai** [chrisckchang/mean-contactlist-angular2#12]
I've spent about an hour trying to figure this out and haven't had much luck. NPM is blaming this module so I figure I'd see if you can help :)
<img width="1440" alt="screen shot 2017-10-03 at 7 24 22 pm" src="https://user-images.githubusercontent.com/6846214/31153777-fc36c0e6-a870-11e7-9b58-2de4182dfb37.png">

**Comment by tfogo** [comment]
Hey, we'll see if we can help. Are you trying to build this project (mean-contactlist-angular2) or a different project that is built on top of this?

**Comment by braelyn-ai** [comment]
I have absolutely no idea. It's the weirdest thing. I don't think I've done anything with this project, but npm is pointing in this direction. Any help is greatly appreciated!

**Comment by tfogo** [comment]
What's the project you're trying to run? Can you send us a link?

Sounds like somebody has modified this project and that's what you're working with.

**Comment by braelyn-ai** [comment]
I can give you temporary access, but it's on a private repo. I will email you an invite. Thank you!!

**Comment by braelyn-ai** [comment]
Turns out the project was built with a tutorial that used this repo as an
example

--

Brandon Boynton
Vemity <http://vemity.com> Founder and CEO
@bboynton97 <http://twitter.com/bboynton97> | @VemityAI
<http://twitter.com/VemityAI>

**Comment by tfogo** [comment]
Hey the invite isn't working for some reason. Can you resend the invite? 

I'll take a quick look at it for you. But it looks like the project's heavily modified so I may not be able to help very much to be honest.

**Comment by braelyn-ai** [comment]
Hey! I got it fixed. That bug was really strange. Thank you for your willingness to help! :+1: :+1: :+1:

**Comment by tfogo** [comment]
Great to hear! Glad you fixed it 👍
