### ISSUE TITLE
Where is CONTACTS_COLLECTION schema defined?

### ISSUE THREAD

**Issue by francedance** [chrisckchang/mean-contactlist-angular2#13]
https://github.com/chrisckchang/mean-contactlist-angular2/blob/f5df5efb1de0f98ea106fb3254f5b3a0f5e51723/server.js#L6

I've realized that CONTACTS_COLLECTION is just set to a string called "contacts"..not really a Schema or a model for MongoDB

https://github.com/chrisckchang/mean-contactlist-angular2/blob/f5df5efb1de0f98ea106fb3254f5b3a0f5e51723/server.js#L50

Here, you're using CONTACTS_COLLECTION (which I assume is just a string "contacts")... I am sorry, I don't get the logic here. Have you declared Schema for CONTACTS_COLLECTION somewhere else? 

Thank you

**Comment by chrisckchang** [comment]
@francedance CONTACTS_COLLECTION is a const that we create for convenience. we should probably change `var CONTACTS_COLLECTION = "contacts";` to `const CONTACTS_COLLECTION = "contacts"; `
