### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by JPhomma** [chrisckchang/mean-contactlist-angular2#14]
Hi,

I am seeing the current error in my console:

GET https://radiant-ridge-88002.herokuapp.com/favicon.ico 503 (Service Unavailable)

I was following the Heroku tutorial and im not sure where I went wrong.

Thanks in advance for any help!

**Comment by tfogo** [comment]
Looks like your Heroku app didn't build and start correctly. To find out what went wrong, you'll need to look at the [Heroku logs](https://devcenter.heroku.com/articles/logging) by running `heroku logs` on your shell.

Those logs should tell you what the issue is. If you still can't fix the problem, feel free to paste the logs here and we'll take a look.

**Comment by JPhomma** [comment]
Thank you for your response tfogo.

I've resolved one issue, I had my server.js file in the src directory. I moved it out to the correct place but I am getting different errors now.

Here are my logs:

module.js:471
throw err;

Error:    Cannot find module '/app/server.js'
at Function.Module._load (module.js:417:25)
at Function.Module._resolveFilename (module.js:469:15)
 at Module.runMain (module.js:604:10)
 at run (bootstrap_node.js:383:7)
 at bootstrap_node.js:496:3
 at startup (bootstrap_node.js:149:9)

When viewing my web application all i can see is the text "Cannot GET /" and nothing else.

**Comment by tfogo** [comment]
Great to hear you fixed one error! Is that the new error? 

See how it says `Error: Cannot find module '/app/server.js'`? This means Node is trying to run a file at `/app/server.js`. Your `server.js` file should be in the top level of your project directory. You should do 2 things to make sure everything is okay:

1. Double check your directory structure by comparing it to the [code in this repository](https://github.com/chrisckchang/mean-contactlist-angular2). Make sure every file is where it should be.

2. Compare your `package.json` file to the [one in this repository](https://github.com/chrisckchang/mean-contactlist-angular2/blob/master/package.json#L7). If you're running `npm start` to start your program, your `package.json` defines what file it runs. It's possible your file might say `"start": "node /app/server.js"` when it should just say `"start": "node server.js"`.

**Comment by JPhomma** [comment]
Resolved!

There were three changes I made before the build was able start correctly:

1. I somehow missed a line of code in the handleError and the end of contact.service.ts

2. I didn't add the "postinstall": "ng build" in the package.json file

3. I was missing the whole app.json file


Thanks for your help!

**Comment by tfogo** [comment]
Great to hear! If you have any more questions, let us know.
