### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by amandeepmittal** [chrisckchang/mean-contactlist-angular2#2]
As mentioned in the article [here](https://devcenter.heroku.com/articles/mean-apps-restful-api), [demo link](https://tranquil-shore-75468.herokuapp.com/) given is not working.

**Comment by rhnorment** [comment]
+1

**Comment by chrisckchang** [comment]
currently working for me- can you please share with me what you're seeing?

**Comment by amandeepmittal** [comment]
I was seeing typical Heroku Application Error earlier, but it's working fine now. Maybe something was tjere the other day.
