### ISSUE TITLE
Pressing the "Deploy on Heroku" button doesn't work

### ISSUE THREAD

**Issue by winstonma** [chrisckchang/mean-contactlist-angular2#3]
The error are as follows:

> No app.json located in the repo URL provided.
> 
> Make sure that an app.json file exists in the project root directory.

Thanks a lot

**Comment by chrisckchang** [comment]
should be fixed with PR https://github.com/chrisckchang/mean-contactlist-angular2/pull/5. please let me know if you're still having difficulties!
