### ISSUE TITLE
Please help update the main documentation

### ISSUE THREAD

**Issue by winstonma** [chrisckchang/mean-contactlist-angular2#4]
On the [Create a Web App and RESTful API Server Using the MEAN Stack - Prerequisites](https://devcenter.heroku.com/articles/mean-apps-restful-api#prerequisites), it requires to install the app `npm install -g angular-cli`. But in the package.json it is already using `@angular/cli`.

So I would suggest updating the document to `npm install -g @angular/cli`. Thanks

**Comment by chrisckchang** [comment]
fixed, thanks!

**Comment by winstonma** [comment]
I guess the npm package is incorrect. I got the following error message:

> npm ERR! code EINVALIDTAGNAME
> npm ERR! Invalid tag name "@angular-cli": Tags may not have any characters that encodeURIComponent encodes.

I guess the correct package is `@angular/cli` not `@angular-cli`.
